<a href="https://colab.research.google.com/github/won195/TIL/blob/master/%5BSummary_%EC%8B%9C%EB%A6%AC%EC%A6%88_2%5D_30%EB%B6%84_Numpy%2C_Pandas_%EC%9A%94%EC%95%BD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# [Summary 시리즈 2] 30분 Numpy, Pandas 요약

In [1]:
import numpy as np

In [2]:
data = [[1,2,3],[4,5,6],[7,8,9,]]

a= np.array(data)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
a.dtype

dtype('int64')

In [4]:
a = a.astype(np.float32)
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [5]:
a[0][1]

2.0

In [6]:
a[0]

array([1., 2., 3.], dtype=float32)

In [7]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [8]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(1,13).reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [10]:
np.nan * 10

nan

In [11]:
a[0][1] = np.nan

In [12]:
a

array([[ 1., nan,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]], dtype=float32)

In [13]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
a = np.linspace(1,10,10)
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

# 연산

In [18]:
data = np.arange(1,10).reshape(3,3)
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
data + data 

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [20]:
data * data

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [21]:
data / data

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.dot(data,data)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [23]:
data@data

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

# 차원

In [24]:
# 0 차원 : 스칼라
a = np.array(1)
a
a.shape
a.ndim

0

In [25]:
# 1 차원 : 스칼라
a = np.array([1])
a
a.shape
a.ndim

1

In [26]:
# 2 차원 : 메트릭스
a = np.array([[1,2,3],[4,5,6]])
a
a.shape
a.ndim

2

In [27]:
# 3 차원 : 3차원 이상의 다차원의 행렬을 Tensor
a = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
a
a.shape
#a.ndim

(2, 3, 2)

# matrix의 유형

In [28]:
a = np.arange(12).reshape(2,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [29]:
b = np.ones(12)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [30]:
b = np.ones(12).reshape(2,3,2)
b

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [31]:
c = np.zeros(12).reshape(2,3,2)
c

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [32]:
d = np.eye(3)
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
c = np.zeros([3,4])
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
e = np.zeros([3,4,2])
e

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [35]:
f = np.empty([2,3])
f

array([[4.9e-324, 9.9e-324, 1.5e-323],
       [2.0e-323, 2.5e-323, 3.0e-323]])

In [36]:
g = np.full((3,4),1000)
g

array([[1000, 1000, 1000, 1000],
       [1000, 1000, 1000, 1000],
       [1000, 1000, 1000, 1000]])

In [37]:
h = np.linspace(2, 10, 6)
h

array([ 2. ,  3.6,  5.2,  6.8,  8.4, 10. ])

# 집계 함수

In [38]:
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [39]:
a[0][0] = 100
a

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [40]:
a[0][1] = 1000
a

array([[ 100, 1000,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [41]:
np.mean(a) # 평균

114.4

In [42]:
np.median(a) # 중앙값

6.5

In [43]:
np.std(a)  # 표준편차

296.5485457728633

In [44]:
np.var(a) #분산

87941.04

In [45]:
np.sum(a)

1144

In [46]:
sum(a)

array([ 105, 1006,    9,   11,   13])

In [47]:
a

array([[ 100, 1000,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [48]:
np.sum(a, axis=0)

array([ 105, 1006,    9,   11,   13])

In [49]:
np.sum(a, axis=1)

array([1109,   35])

In [50]:
np.max(a)

1000

In [51]:
np.min(a)

2

# 2. Pandas

In [52]:
import pandas as pd

In [53]:
data = np.arange(0,50,10 )
data

array([ 0, 10, 20, 30, 40])

In [54]:
a = pd.Series(data, index=['a','b','c','d','e'])
a.astype('int32')

a     0
b    10
c    20
d    30
e    40
dtype: int32

In [55]:
b = pd.Series(data)
b.astype('int32')

0     0
1    10
2    20
3    30
4    40
dtype: int32

In [56]:
a['b']

10

In [57]:
a.loc['b']

10

In [58]:
a.iloc[1]

10

# 산술연산

In [59]:
a

a     0
b    10
c    20
d    30
e    40
dtype: int64

In [61]:
a + 10
a - 10
a * 10
a ** 2
a / 5
a // 5
a % 3 

a    0
b    1
c    2
d    0
e    1
dtype: int64

In [62]:
a

a     0
b    10
c    20
d    30
e    40
dtype: int64

In [65]:
a[a > 15]

c    20
d    30
e    40
dtype: int64

# 집계함수

In [66]:
a.add(100)

a    100
b    110
c    120
d    130
e    140
dtype: int64

In [67]:
a.sub(100)

a   -100
b    -90
c    -80
d    -70
e    -60
dtype: int64

In [68]:
a.mul(100)

a       0
b    1000
c    2000
d    3000
e    4000
dtype: int64

In [69]:
a.div(100)

a    0.0
b    0.1
c    0.2
d    0.3
e    0.4
dtype: float64

In [70]:
a.mod(3)

a    0
b    1
c    2
d    0
e    1
dtype: int64

In [71]:
a.min()

0

In [72]:
a.max()

40

In [73]:
a.sum()

100

In [74]:
a.mean()

20.0

In [75]:
a.median()

20.0

In [76]:
a.std()

15.811388300841896

In [77]:
a.var()

250.0

# DataFrame

In [80]:
rawData = np.random.randint(50, 100, size=(4,3))
rawData

array([[98, 98, 95],
       [93, 83, 81],
       [92, 57, 55],
       [85, 77, 66]])

In [81]:
df = pd.DataFrame(rawData, index=['1반','2반','1반','2반'], columns=['국','영','수'])
df

국   영   수
1반  98  98  95
2반  93  83  81
1반  92  57  55
2반  85  77  66

In [82]:
df['국']

1반    98
2반    93
1반    92
2반    85
Name: 국, dtype: int64

In [93]:
df['평균'] = round((df['국'] + df['영'] + df['수'])/3, 2)
df

국   영   수     평균
1반  98  98  95  97.00
2반  93  83  81  85.67
1반  92  57  55  68.00
2반  85  77  66  76.00

In [94]:
df['na'] = np.nan
df

국   영   수     평균  na
1반  98  98  95  97.00 NaN
2반  93  83  81  85.67 NaN
1반  92  57  55  68.00 NaN
2반  85  77  66  76.00 NaN

In [95]:
del df['na']
df

국   영   수     평균
1반  98  98  95  97.00
2반  93  83  81  85.67
1반  92  57  55  68.00
2반  85  77  66  76.00

In [96]:
df[df.평균 > 75]

국   영   수     평균
1반  98  98  95  97.00
2반  93  83  81  85.67
2반  85  77  66  76.00

In [98]:
df = df.drop(['평균'],axis='columns')
df

국   영   수
1반  98  98  95
2반  93  83  81
1반  92  57  55
2반  85  77  66

# 결측값 처리

In [99]:
df = df.astype('float64')

In [101]:
df['수'][2] = np.nan
df

국     영     수
1반  98.0  98.0  95.0
2반  93.0  83.0  81.0
1반  92.0  57.0   NaN
2반  85.0  77.0  66.0

In [104]:
df.dropna(axis=0)

국     영     수
1반  98.0  98.0  95.0
2반  93.0  83.0  81.0
2반  85.0  77.0  66.0

In [105]:
df

국     영     수
1반  98.0  98.0  95.0
2반  93.0  83.0  81.0
1반  92.0  57.0   NaN
2반  85.0  77.0  66.0

In [106]:
df.dropna(axis=1)

국     영
1반  98.0  98.0
2반  93.0  83.0
1반  92.0  57.0
2반  85.0  77.0

In [107]:
df.fillna(0)

국     영     수
1반  98.0  98.0  95.0
2반  93.0  83.0  81.0
1반  92.0  57.0   0.0
2반  85.0  77.0  66.0

In [108]:
df.fillna(df.mean())

국     영          수
1반  98.0  98.0  95.000000
2반  93.0  83.0  81.000000
1반  92.0  57.0  80.666667
2반  85.0  77.0  66.000000

# MultiIndex

In [109]:
df

국     영     수
1반  98.0  98.0  95.0
2반  93.0  83.0  81.0
1반  92.0  57.0   NaN
2반  85.0  77.0  66.0

In [110]:
df.T

1반    2반    1반    2반
국  98.0  93.0  92.0  85.0
영  98.0  83.0  57.0  77.0
수  95.0  81.0   NaN  66.0

In [111]:
df

국     영     수
1반  98.0  98.0  95.0
2반  93.0  83.0  81.0
1반  92.0  57.0   NaN
2반  85.0  77.0  66.0

In [112]:
df.index = [['1학년','1학년','2학년','2학년'],['1반','2반','1반','2반']]
df

국     영     수
1학년 1반  98.0  98.0  95.0
    2반  93.0  83.0  81.0
2학년 1반  92.0  57.0   NaN
    2반  85.0  77.0  66.0

In [115]:
df.columns = [['언어','언어','수리'],['국', '영', '수']]
df

언어          수리
           국     영     수
1학년 1반  98.0  98.0  95.0
    2반  93.0  83.0  81.0
2학년 1반  92.0  57.0   NaN
    2반  85.0  77.0  66.0

In [116]:
df['언어']['국']

1학년  1반    98.0
     2반    93.0
2학년  1반    92.0
     2반    85.0
Name: 국, dtype: float64

In [119]:
df.iloc[0]

언어  국    98.0
    영    98.0
수리  수    95.0
Name: (1학년, 1반), dtype: float64

In [117]:
df.loc['1학년']

언어          수리
       국     영     수
1반  98.0  98.0  95.0
2반  93.0  83.0  81.0

In [120]:
df.loc['1학년'].loc['1반']

언어  국    98.0
    영    98.0
수리  수    95.0
Name: 1반, dtype: float64

# 데이터 사전분석

In [121]:
df

언어          수리
           국     영     수
1학년 1반  98.0  98.0  95.0
    2반  93.0  83.0  81.0
2학년 1반  92.0  57.0   NaN
    2반  85.0  77.0  66.0

In [122]:
df.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4 entries, ('1학년', '1반') to ('2학년', '2반')
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   (언어, 국)  4 non-null      float64
 1   (언어, 영)  4 non-null      float64
 2   (수리, 수)  3 non-null      float64
dtypes: float64(3)
memory usage: 384.0+ bytes


In [123]:
df.head()

언어          수리
           국     영     수
1학년 1반  98.0  98.0  95.0
    2반  93.0  83.0  81.0
2학년 1반  92.0  57.0   NaN
    2반  85.0  77.0  66.0

In [124]:
df.tail()

언어          수리
           국     영     수
1학년 1반  98.0  98.0  95.0
    2반  93.0  83.0  81.0
2학년 1반  92.0  57.0   NaN
    2반  85.0  77.0  66.0

In [125]:
df.dtypes

언어  국    float64
    영    float64
수리  수    float64
dtype: object

In [126]:
df.describe()

언어                    수리
               국          영          수
count   4.000000   4.000000   3.000000
mean   92.000000  78.750000  80.666667
std     5.354126  16.977927  14.502873
min    85.000000  57.000000  66.000000
25%    90.250000  72.000000  73.500000
50%    92.500000  80.000000  81.000000
75%    94.250000  86.750000  88.000000
max    98.000000  98.000000  95.000000

In [128]:
df.isnull().sum()

언어  국    0
    영    0
수리  수    1
dtype: int64

#값의 연결

In [129]:
a = pd.DataFrame(np.arange(1, 10).reshape(3,3))
a

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [130]:
b = pd.Series(np.arange(10,40,10))
b

0    10
1    20
2    30
dtype: int64

In [135]:
pd.concat([a,b],axis=1,ignore_index=True)

0  1  2   3
0  1  2  3  10
1  4  5  6  20
2  7  8  9  30

In [136]:
a.append(b,ignore_index=True)

<ipython-input-136-9f6f53509836>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  a.append(b,ignore_index=True)


0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  20  30