<a href="https://colab.research.google.com/github/won195/TIL/blob/master/%5BSummary_%EC%8B%9C%EB%A6%AC%EC%A6%88_2%5D_30%EB%B6%84_Numpy%2C_Pandas_%EC%9A%94%EC%95%BD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# [Summary 시리즈 2] 30분 Numpy, Pandas 요약

In [1]:
import numpy as np

In [3]:
data = [[1,2,3],[4,5,6],[7,8,9,]]

a= np.array(data)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
a.dtype

dtype('int64')

In [8]:
a = a.astype(np.float32)
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [9]:
a[0][1]

2.0

In [10]:
a[0]

array([1., 2., 3.], dtype=float32)

In [11]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [12]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.arange(1,13).reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [15]:
np.nan * 10

nan

In [16]:
a[0][1] = np.nan

In [17]:
a

array([[ 1., nan,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]], dtype=float32)

In [18]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
a[0][1] = np.nan

ValueError: ignored

In [20]:
a = np.linspace(1,10,10)
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

# 연산

In [21]:
data = np.arange(1,10).reshape(3,3)
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
data + data 

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [23]:
data * data

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [25]:
data / data

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
np.dot(data,data)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [27]:
data@data

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

# 차원

In [30]:
# 0 차원 : 스칼라
a = np.array(1)
a
a.shape
a.ndim

0

In [31]:
# 1 차원 : 스칼라
a = np.array([1])
a
a.shape
a.ndim

1

In [33]:
# 2 차원 : 메트릭스
a = np.array([[1,2,3],[4,5,6]])
a
a.shape
a.ndim

2

In [34]:
# 3 차원 : 3차원 이상의 다차원의 행렬을 Tensor
a = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
a
a.shape
#a.ndim

(2, 3, 2)

# matrix의 유형

In [36]:
a = np.arange(12).reshape(2,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [37]:
b = np.ones(12)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [38]:
b = np.ones(12).reshape(2,3,2)
b

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [41]:
c = np.zeros(12).reshape(2,3,2)
c

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [43]:
d = np.eye(3)
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
c = np.zeros([3,4])
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [45]:
e = np.zeros([3,4,2])
e

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [47]:
f = np.empty([2,3])
f

array([[4.9e-324, 9.9e-324, 1.5e-323],
       [2.0e-323, 2.5e-323, 3.0e-323]])

In [48]:
g = np.full((3,4),1000)
g

array([[1000, 1000, 1000, 1000],
       [1000, 1000, 1000, 1000],
       [1000, 1000, 1000, 1000]])

In [49]:
h = np.linspace(2, 10, 6)
h

array([ 2. ,  3.6,  5.2,  6.8,  8.4, 10. ])

# 집계 함수

In [51]:
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [52]:
a[0][0] = 100
a

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [53]:
a[0][1] = 1000
a

array([[ 100, 1000,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [54]:
np.mean(a) # 평균

114.4

In [55]:
np.median(a) # 중앙값

6.5

In [56]:
np.std(a)  # 표준편차

296.5485457728633

In [57]:
np.var(a) #분산

87941.04

In [58]:
np.sum(a)

1144

In [59]:
sum(a)

array([ 105, 1006,    9,   11,   13])

In [60]:
a

array([[ 100, 1000,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [61]:
np.sum(a, axis=0)

array([ 105, 1006,    9,   11,   13])

In [62]:
np.sum(a, axis=1)

array([1109,   35])

In [63]:
np.max(a)

1000

In [64]:
np.min(a)

2

# 2. Pandas

In [65]:
import pandas as pd

In [70]:
data = np.arange(0,50,10 )
data

array([ 0, 10, 20, 30, 40])

In [71]:
a = pd.Series(data, index=['a','b','c','d','e'])
a.astype('int32')

a     0
b    10
c    20
d    30
e    40
dtype: int32

In [72]:
b = pd.Series(data)
b.astype('int32')

0     0
1    10
2    20
3    30
4    40
dtype: int32

In [73]:
a['b']

10

In [74]:
a.loc['b']

10

In [75]:
a.iloc[1]

10