<a href="https://colab.research.google.com/github/won195/TIL/blob/master/%E1%84%91%E1%85%A1%E1%84%8B%E1%85%B5%E1%84%90%E1%85%A9%E1%84%8E%E1%85%B5_%ED%95%99%EC%8A%B5%EC%8B%9C_%EB%84%98%ED%8C%8C%EC%9D%B4_ndarray%EB%A5%BC_%EB%B0%94%EB%A1%9C_%EC%93%B8_%EC%88%98_%EC%97%86%EB%8B%A4%3F!_%ED%85%90%EC%84%9C_torch_Tensor_API_%EC%95%8C%EC%95%84%EB%B3%B4%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

In [ ]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
type(data), type(x_data)

(list, torch.Tensor)

In [ ]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

type(np_array), type(x_np), type(x_np.numpy())

(numpy.ndarray, torch.Tensor, numpy.ndarray)

In [ ]:
x_ones = torch.ones_like(x_data)
print(f"ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.1917, 0.1524],
        [0.1297, 0.5304]]) 



In [ ]:
np.ones(x_data.shape), np.ones_like(x_data)

(array([[1., 1.],
        [1., 1.]]),
 array([[1, 1],
        [1, 1]]))

In [ ]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.9336, 0.6154, 0.4154],
        [0.9225, 0.6027, 0.5210]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on :{tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on :cpu


In [ ]:
if torch.cuda.is_available():
  tensor = tensor.to("cuda")

In [ ]:
tensor.device

device(type='cuda', index=0)

In [ ]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:, 1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [ ]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [ ]:
torch.vstack([tensor, tensor, tensor]).shape

torch.Size([12, 4])

In [ ]:
torch.hstack([tensor, tensor, tensor]).shape

torch.Size([4, 12])

In [21]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [23]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [25]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]]) 

tensor([[11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.]])


In [29]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"t: {n}")
type(t), type(n)

t: tensor([1., 1., 1., 1., 1.])
t: [1. 1. 1. 1. 1.]


(torch.Tensor, numpy.ndarray)

In [28]:
t.add_(1)
print(f"t: {t}")
print(f"t: {n}")

t: tensor([2., 2., 2., 2., 2.])
t: [2. 2. 2. 2. 2.]


In [30]:
n = np.ones(5)
t = torch.from_numpy(n)
type(n), type(t)

(numpy.ndarray, torch.Tensor)

In [31]:
torch.Tensor(n)

tensor([1., 1., 1., 1., 1.])

In [33]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"t: {n}")

t: tensor([3., 3., 3., 3., 3.], dtype=torch.float64)
t: [3. 3. 3. 3. 3.]
