<a href="https://colab.research.google.com/github/won195/TIL/blob/master/%ED%85%90%EC%84%9C%ED%94%8C%EB%A1%9C%EC%9A%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
x = tf.ones(shape=(2,1))
x

In [2]:
import numpy as np
n = np.ones(shape=(2,1))
print(f'{n}, shape={n.shape},dtype={n.dtype}')

[[1.]
 [1.]], shape=(2, 1),dtype=float64


In [3]:
x = tf.zeros(shape=(2,1))
x

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[0.],
       [0.]], dtype=float32)>

In [4]:
n = np.zeros(shape=(2,1))
print(f'{n}, shape={n.shape},dtype={n.dtype}')

[[0.]
 [0.]], shape=(2, 1),dtype=float64


In [15]:
# 랜덤 텐서

x = tf.random.normal(shape=(3, 1), mean=0., stddev=1.)   # mean: 평균 / stddev: 표준편차
print(x)

x = tf.random.uniform(shape=(3, 1), minval=0., maxval=1.)  # minval: 최소값., maxval: 최대값
print(x)

tf.Tensor(
[[-0.9064317 ]
 [ 0.22730266]
 [ 1.5021167 ]], shape=(3, 1), dtype=float32)
tf.Tensor(
[[0.05790389]
 [0.7855625 ]
 [0.5748899 ]], shape=(3, 1), dtype=float32)


In [16]:
# 텐서플로 변수 만들기

v = tf.Variable(initial_value=tf.random.normal(shape=(3, 1)))    # tf.Variable(): 텐서값을 저장하는 변수, initial_value: 변수의 초기값 지정
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[-1.8177731],
       [ 1.4223384],
       [-1.3746146]], dtype=float32)>


In [17]:
# 텐서에 변수값 할당

v.assign(tf.ones((3, 1)))   # assign: 새로운 값 할당

# tf.zeros(): 모든 원소가 0인 텐서 생성 함수
# tf.ones(): 모든 원소가 1인 텐서 생성 함수
# tf.fill(): 지정한 값으로 채워진 텐서 생성 함수
# tf.constant(): 상수(constant) 값을 가지는 텐서 생성 함수
# tf.add(): 두 개의 텐서를 더하는 함수
# tf.subtract(): 두 개의 텐서를 빼는 함수
# tf.multiply(): 두 개의 텐서를 곱하는 함수
# tf.divide(): 두 개의 텐서를 나누는 함수

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>

In [18]:
# 기존값에 +, -
a = v.assign_add(tf.ones((3, 1)))
print(a)
b = v.assign_sub(tf.ones((3, 1)))
print(b)

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[2.],
       [2.],
       [2.]], dtype=float32)>
<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>


In [19]:
# 텐서플로우를 이용한 배열 생성
t = tf.Variable(initial_value=[[1,2],[3,4]], dtype=tf.float32)
t

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [20]:
# 텐서플로우의 연산
b = tf.square(t)
print(b)
c = tf.sqrt(b)
print(c)
d = b + c
e = b * c
f = b / c 

tf.Tensor(
[[ 1.  4.]
 [ 9. 16.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
