<a href="https://colab.research.google.com/github/won195/TIL/blob/master/%ED%8C%8C%EC%9D%B4%EC%8D%AC_%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D_%EA%B0%95%EC%9D%98_02_2_%ED%8C%8C%EC%9D%B4%EC%8D%AC_NumPy_%EC%A3%BC%EC%9A%94_%ED%95%A8%EC%88%98_%EB%B0%8F_%EA%B8%B0%EB%8A%A5_%EC%A0%95%EB%A6%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 파이썬 머신러닝 강의 02-2 - 파이썬 NumPy 주요 함수 및 기능 정리

In [1]:
import numpy as np

In [2]:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [3]:
np.array([1,2,3,4],dtype='float')

array([1., 2., 3., 4.])

In [4]:
np.array([range(i, i + 3)for i in [1,4,7]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [12]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [16]:
np.linspace(0, 100, 5, dtype=int)

array([  0,  25,  50,  75, 100])

In [18]:
np.random.random((3,3))

array([[0.99441299, 0.37259511, 0.71315258],
       [0.05957823, 0.15100548, 0.20059499],
       [0.65635734, 0.55869832, 0.40855434]])

In [19]:
np.random.randint(0, 10, (3,3))

array([[3, 1, 6],
       [2, 5, 0],
       [3, 1, 0]])

In [21]:
np.random.normal(0,1,(3,3))

array([[ 1.30779238, -0.08583268,  0.56853308],
       [-0.99083718,  1.24289898, -0.88322148],
       [ 0.07519828, -0.74601118,  0.67667289]])

In [24]:
np.random.seed(0)

arr1 = np.random.randint(10, size=6)
arr2 = np.random.randint(10, size=(2,3))

print('arr1:\n%s' % arr1)
print("ndim: %d, shape: %s, size: %d, dtype: %s\n"%(arr1.ndim, arr1.shape, arr1.size, arr1.dtype))

print('arr1:\n$s' % arr2)
print("ndim: %d, shape: %s, size: %d, dtype: %s\n"%(arr2.ndim, arr2.shape, arr2.size, arr2.dtype))

arr1:
[5 0 3 3 7 9]
ndim: 1, shape: (6,), size: 6, dtype: int64

arr1:
$s
ndim: 2, shape: (2, 3), size: 6, dtype: int64



In [25]:
arr1

array([5, 0, 3, 3, 7, 9])

In [26]:
arr1[0],arr1[5]

(5, 9)

In [27]:
arr1[-6],arr1[-1]

(5, 9)

In [28]:
arr2

array([[3, 5, 2],
       [4, 7, 6]])

In [29]:
arr2[0,0], arr2[0,2]

(3, 2)

In [31]:
arr2[-1,-3],arr2[-1,-1]

(4, 6)

In [32]:
arr2[0,0] = 9
arr2

array([[9, 5, 2],
       [4, 7, 6]])

In [33]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
arr1[0:5:1]

array([0, 1, 2, 3, 4])

In [35]:
arr1[:5:1]

array([0, 1, 2, 3, 4])

In [36]:
arr1[:5:],arr1[:5]

(array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4]))

In [37]:
arr1[:],arr1[::]

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [38]:
arr1[2:9:2], arr1[2::2]

(array([2, 4, 6, 8]), array([2, 4, 6, 8]))

In [40]:
arr1[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [42]:
arr1[-1:-11:-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [43]:
arr1[5::-1]

array([5, 4, 3, 2, 1, 0])

In [44]:
arr2 = np.arange(12).reshape(-1,4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
arr2[:3,:4]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
arr2[:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
arr2[:2,:3]

array([[0, 1, 2],
       [4, 5, 6]])

In [49]:
arr2[:2,2::-1]

array([[2, 1, 0],
       [6, 5, 4]])

In [50]:
arr2[1:-1]

array([[4, 5, 6, 7]])

In [52]:
arr2[-1,:],arr2[-1]

(array([ 8,  9, 10, 11]), array([ 8,  9, 10, 11]))

In [53]:
list1 = [1,2,3]
list2 = [4,5,6]

In [54]:
np.concatenate([list1,list2])

array([1, 2, 3, 4, 5, 6])

In [56]:
arr1 = np.concatenate([list1,list2],axis=0)
arr1

array([1, 2, 3, 4, 5, 6])

In [57]:
arr2 = arr1.reshape(-1,3)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
np.concatenate([arr2,arr2], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [59]:
np.concatenate([arr2,arr2],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [60]:
np.vstack([arr2,arr2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [61]:
np.hstack([arr2,arr2])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [62]:
np.random.seed(0)

arr2 = np.random.randint(1,10,(3,4))
arr2

array([[6, 1, 4, 4],
       [8, 4, 6, 3],
       [5, 8, 7, 9]])

In [65]:
np.sum(arr2),arr2.sum()

(65, 65)

In [66]:
np.sum(arr2, axis=0), arr2.sum(axis=0)

(array([19, 13, 17, 16]), array([19, 13, 17, 16]))

In [67]:
np.sum(arr2, axis=0), arr2.sum(axis=1)

(array([19, 13, 17, 16]), array([15, 21, 29]))

In [68]:
 np.min(arr2, axis=0), np.max(arr2,axis=0)

(array([5, 1, 4, 3]), array([8, 8, 7, 9]))

In [69]:
arr2

array([[6, 1, 4, 4],
       [8, 4, 6, 3],
       [5, 8, 7, 9]])